lint:
  files_exist:
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .pre-commit-config.yaml
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  nextflow_config:
    - config_defaults:
        - params.mtbseq_ref_and_indexes_path
        - params.mtbseq_resilist
        - params.mtbseq_intregions
        - params.mtbseq_categories
        - params.mtbseq_basecalib
  nf_test_content: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: "@abhi18av"
  description: TB-GVAS aims to democratize analysis by providing a comprehensive and
    user-friendly toolkit for genomic characterization of Mycobacterium tuberculosis
    (Mtb) pathogens at the species and strain levels
  force: false
  is_nfcore: true
  name: tbanalyzer
  org: nf-core
  outdir: .
  version: 1.0dev
